import { seed } from "../src/data/seed.ts";
import { writeFileSync } from "node:fs";
const tables = [
  "categories",
  "providers",
  "capabilities",
  "products",
  "use_cases",
  "solution_stacks",
  "integrators",
  "consultants",
  "articles",
  "updates",
];
// Row provenance follows the record: sample rows are 'demo', vendor-sourced rows keep
// 'third-party sourced', editorial taxonomy rows keep 'inferred'.
const rowProvenance = (record) => (["demo", "third-party sourced", "inferred"].includes(record.provenance) ? record.provenance : "demo");
const sqlText = (value) => "'" + String(value).replaceAll("'", "''") + "'";
let sql =
  "-- Clearly labelled sample catalogue. No fictional ratings or deployment claims.\n" +
  "-- Generated by scripts/export-seed.mjs. Run as the database administrator after all migrations.\n";
// Taxonomy first: use_cases reference categories through generated columns.
const categories = [...(seed.use_case_categories ?? [])].sort((a, b) => (a.level === b.level ? 0 : a.level === "category" ? -1 : 1));
for (const c of categories)
  sql += `insert into public.use_case_categories(id,slug,name,description,level,"parentId","sortOrder",provenance) values (${sqlText(c.id)},${sqlText(c.slug)},${sqlText(c.name)},${sqlText(c.description ?? "")},${sqlText(c.level)},${c.parentId ? sqlText(c.parentId) : "null"},${Number(c.sortOrder ?? 0)},${sqlText(c.provenance ?? "inferred")}) on conflict(id) do update set name=excluded.name,description=excluded.description,"sortOrder"=excluded."sortOrder";\n`;
for (const table of tables)
  for (const record of seed[table] ?? []) {
    // Only approved Use Cases are published; merged or archived ones stay unpublished.
    const published = table === "use_cases" ? (record.status ?? "approved") === "approved" : true;
    sql += `insert into public.${table}(id,data,published,provenance) values ('${record.id.replaceAll("'", "''")}','${JSON.stringify(record).replaceAll("'", "''")}'::jsonb,${published},'${rowProvenance(record)}') on conflict(id) do update set data=excluded.data;\n`;
  }
// Typed taxonomy tables: only listed columns, arrays as text[], absent values omitted.
const typed = {
  use_case_sources: ["id", "name", "useCaseId", "sourceType", "sourceEntityId", "originalTitle", "originalDescription", "productIds", "sourceUrl", "retrievedAt", "lastCheckedAt", "captureMethod", "attribution", "status", "provenance"],
  use_case_aliases: ["id", "name", "useCaseId", "label", "aliasType", "normalizedLabel", "language", "source", "provenance"],
  use_case_redirects: ["id", "name", "fromSlug", "targetType", "target", "reason", "provenance"],
};
for (const [table, columns] of Object.entries(typed))
  for (const record of seed[table] ?? []) {
    const present = columns.filter((column) => record[column] !== undefined && record[column] !== null);
    const values = present.map((column) =>
      Array.isArray(record[column]) ? (record[column].length ? `ARRAY[${record[column].map(sqlText).join(",")}]::text[]` : "'{}'::text[]") : sqlText(record[column]),
    );
    sql += `insert into public.${table}(${present.map((column) => '"' + column + '"').join(",")}) values (${values.join(",")}) on conflict do nothing;\n`;
  }
writeFileSync("supabase/seed.sql", sql);
// Optional Build examples require three real, explicitly supplied Auth user IDs.
// Run as the database administrator; never create seeded passwords or login identities.
const quote = (value) => "'" + String(value).replaceAll("'", "''") + "'";
const owners = {
  "demo-user": "demo_owner_id",
  "demo-studio": "demo_studio_id",
  "demo-maya": "demo_maya_id",
};
let graph =
  "-- Optional fictional Build examples. Supply psql variables demo_owner_id, demo_studio_id, demo_maya_id (existing Auth UUIDs).\nBEGIN;\n";
graph += `insert into public.organizations(id,data,published,provenance) values('northstar','{"id":"northstar","name":"Northstar Studio","provenance":"demo"}',true,'demo') on conflict(id) do nothing;\n`;
for (const c of seed.creator_profiles ?? []) {
  const keys = Object.keys(c),
    values = keys.map((k) =>
      k === "ownerId"
        ? `:'${owners[c.ownerId]}'::uuid`
        : Array.isArray(c[k])
          ? `ARRAY[${c[k].map(quote).join(",")}]::text[]`
          : typeof c[k] === "boolean"
            ? String(c[k])
            : quote(c[k]),
    );
  graph += `insert into public.creator_profiles(${keys.map((k) => '"' + k + '"').join(",")}) values(${values.join(",")}) on conflict(id) do nothing;\n`;
}
for (const b of seed.builds ?? [])
  graph += `select set_config('request.jwt.claims',jsonb_build_object('sub', :'${owners[b.ownerId]}','role','service_role')::text,true);\nselect public.save_build(${quote(JSON.stringify(b))}::jsonb || jsonb_build_object('ownerId', :'${owners[b.ownerId]}'));\n`;
for (const o of seed.build_offers ?? []) {
  const keys = Object.keys(o),
    values = keys.map((k) =>
      k === "ownerId"
        ? `:'${owners[o.ownerId]}'::uuid`
        : o[k] === null
          ? "null"
          : typeof o[k] === "boolean" || typeof o[k] === "number"
            ? String(o[k])
            : quote(o[k]),
    );
  graph += `insert into public.build_offers(${keys.map((k) => '"' + k + '"').join(",")}) values(${values.join(",")}) on conflict(id) do nothing;\n`;
}
graph += "COMMIT;\n";
writeFileSync("supabase/seed-builds.sql", graph);
