export const publicRoutes = [
  "/",
  "/explore",
  "/search",
  "/implementations",
  "/blueprints",
  "/solution-compiler",
  "/builds",
  "/collections",
  "/use-cases",
  "/solution-stacks",
  "/technologies",
  "/categories",
  "/solution-providers",
  "/technology-vendors",
  "/marketplace",
  "/compare",
  "/compare/implementations",
  "/updates",
  "/resources",
  "/about",
  "/how-it-works",
  "/pricing",
  "/contact",
  "/press",
  "/careers",
  "/security",
  "/trust",
  "/accessibility",
  "/terms",
  "/privacy",
  "/cookies",
  "/marketplace-terms",
];
export const buyerRoutes = [
  "/app",
  "/app/saved",
  "/app/compare",
  "/app/requirements",
  "/app/solution-runs",
  "/app/projects",
  "/app/projects/new",
  "/app/messages",
  "/app/notifications",
  "/app/profile",
  "/app/settings",
];
export const providerRoutes = [
  "/provider",
  "/provider/company",
  "/provider/implementations",
  "/provider/compatibility",
  "/provider/listings",
  "/provider/listings/new",
  "/provider/leads",
  "/provider/proposals",
  "/provider/messages",
  "/provider/analytics",
  "/provider/media",
  "/provider/verification",
  "/provider/team",
  "/provider/billing",
  "/provider/settings",
];
export const adminRoutes = [
  "/admin",
  "/admin/implementations",
  "/admin/claims",
  "/admin/evidence",
  "/admin/attestations",
  "/admin/blueprints",
  "/admin/compatibility",
  "/admin/staleness",
  "/admin/audit",
  "/admin/users",
  "/admin/providers",
  "/admin/listings",
  "/admin/use-cases",
  "/admin/stacks",
  "/admin/reviews",
  "/admin/projects",
  "/admin/content",
  "/admin/categories",
  "/admin/verification",
  "/admin/moderation",
];
export const authRoutes = [
  "/sign-in",
  "/sign-up",
  "/forgot-password",
  "/onboarding",
];

export const creatorRoutes = [
  "/creator",
  "/creator/implementations",
  "/creator/blueprints",
  "/creator/builds",
  "/creator/builds/new",
  "/creator/offers",
  "/creator/requests",
  "/creator/messages",
  "/creator/analytics",
  "/creator/profile",
  "/creator/settings",
];
export const buildAdminRoutes = [
  "/admin/builds",
  "/admin/creators",
  "/admin/offers",
  "/admin/reports",
  "/admin/vendor-claims",
];
export const buildProviderRoutes = ["/provider/builds", "/provider/claims"];

/** Old public paths kept resolvable by client-side redirects; never listed in the sitemap. */
export const legacyRoutes = ["/creators", "/providers", "/implementers", "/integrators", "/consultants"];
