-- Search derives from readable, published records. Sponsorship is never part of relevance.
create extension if not exists vector;
create table public.search_embeddings(entity_type text not null,entity_id text not null,embedding vector(1536) not null,model text not null,updated_at timestamptz not null default now(),primary key(entity_type,entity_id));
alter table public.search_embeddings enable row level security;
-- No browser grants/policies. Embeddings are generated by a trusted worker only.
create index search_embedding_cosine on public.search_embeddings using hnsw (embedding vector_cosine_ops);
create or replace view public.search_documents with (security_invoker=true) as
 select b.id,b.name,b.tagline description,'Build'::text type,'/builds/'||b.slug path,b.provenance,
 b.description||' '||b.industry||' '||coalesce((select string_agg(p.data->>'name',' ') from public.build_stack_items s join public.products p on p.id=s."productId" where s."buildId"=b.id),'')||' '||coalesce((select string_agg(u.data->>'name',' ') from public.build_use_cases x join public.use_cases u on u.id=x."useCaseId" where x."buildId"=b.id),'')||' '||coalesce((select c.name from public.creator_profiles c where c.id=b."creatorId"),'') body,b."updatedAt" updated_at
 from public.builds b where b.visibility='public' and b.publication='published' and b.moderation='approved'
 union all select id,name,headline,'Creator','/creators/'||slug,provenance,bio||' '||array_to_string(expertise,' '),"createdAt" from public.creator_profiles
 union all select id,data->>'name',data->>'description','Technology','/technologies/'||(data->>'slug'),provenance::text,(data->>'description')||' '||coalesce(data->>'capabilityIds',''),updated_at from public.products where published
 union all select id,data->>'name',data->>'description','Use case','/use-cases/'||(data->>'slug'),provenance::text,coalesce(data->>'outcome',''),updated_at from public.use_cases where published
 union all select id,data->>'name',data->>'description','Provider','/providers/'||(data->>'slug'),provenance::text,coalesce(data->>'specialties',''),updated_at from public.providers where published
 union all select id,data->>'name',data->>'description','Stack','/solution-stacks/'||(data->>'slug'),provenance::text,coalesce(data->>'description',''),updated_at from public.solution_stacks where published
 union all select id,data->>'name',data->>'description','Resource','/resources/'||(data->>'slug'),provenance::text,coalesce(data->>'body',''),updated_at from public.articles where published;
create index build_name_fts on public.builds using gin(to_tsvector('english',name||' '||tagline||' '||description||' '||industry));
create index creator_fts on public.creator_profiles using gin(to_tsvector('english',name||' '||headline||' '||bio));
create or replace function public.search_catalogue(query text,kind text default null,result_limit integer default 40) returns setof jsonb language sql stable security invoker set search_path='' as $$
 with candidates as(select d.*,setweight(to_tsvector('english',coalesce(d.name,'')),'A')||setweight(to_tsvector('english',coalesce(d.description,'')||' '||coalesce(d.body,'')),'B') document from public.search_documents d where kind is null or d.type=kind)
 select to_jsonb(c)-'document'-'body'||jsonb_build_object('score',ts_rank_cd(c.document,websearch_to_tsquery('english',query))) from candidates c where query='' or c.document@@websearch_to_tsquery('english',query) order by ts_rank_cd(c.document,websearch_to_tsquery('english',query)) desc,c.updated_at desc limit least(greatest(result_limit,1),100)
$$;
-- Server-only hybrid search accepts embeddings generated outside the browser. Joins the public
-- document view at query time so hidden/deleted records cannot leak via stale embeddings.
create or replace function public.hybrid_search(query text,query_embedding vector(1536),result_limit integer default 30) returns table(document jsonb,score double precision) language sql stable security invoker set search_path='' as $$
 select to_jsonb(d)-'body', (0.65*ts_rank_cd(to_tsvector('english',d.name||' '||d.body),websearch_to_tsquery('english',query))+0.35*(1-(e.embedding OPERATOR(public.<=>) query_embedding)))::double precision score
 from public.search_documents d join public.search_embeddings e on e.entity_id=d.id and e.entity_type=d.type order by score desc limit least(greatest(result_limit,1),100)
$$;
revoke all on function public.hybrid_search(text,vector,integer) from public;
grant execute on function public.hybrid_search(text,vector,integer) to service_role;
