-- Hybrid retrieval with Reciprocal Rank Fusion (RRF). Server-only: query embeddings are
-- generated by a trusted worker, never in the browser. Candidates come from the
-- security-invoker search_documents view, so private or unapproved records cannot
-- surface through stale embeddings. Structured filters (type) apply before fusion.
-- score = Σ 1/(k + rank_i) over the lexical and semantic rankings (k = 60 by default).
create or replace function public.hybrid_search_rrf(
  query text,
  query_embedding vector(1536),
  kind text default null,
  result_limit integer default 30,
  k integer default 60)
returns table(document jsonb, rrf_score double precision, lexical_rank bigint, semantic_rank bigint)
language sql stable security invoker set search_path=''
as $$
  with docs as (
    select d.* from public.search_documents d where kind is null or d.type = kind
  ),
  lexical as (
    select d.id, d.type, row_number() over (
      order by ts_rank_cd(to_tsvector('english', coalesce(d.name,'') || ' ' || coalesce(d.body,'')), websearch_to_tsquery('english', query)) desc) as r
    from docs d
    where query <> '' and to_tsvector('english', coalesce(d.name,'') || ' ' || coalesce(d.body,'')) @@ websearch_to_tsquery('english', query)
    limit 100
  ),
  semantic as (
    select d.id, d.type, row_number() over (order by e.embedding operator(public.<=>) query_embedding) as r
    from docs d join public.search_embeddings e on e.entity_id = d.id and e.entity_type = d.type
    limit 100
  )
  select to_jsonb(d) - 'body',
         coalesce(1.0 / (k + l.r), 0) + coalesce(1.0 / (k + s.r), 0),
         l.r, s.r
  from docs d
  left join lexical l on l.id = d.id and l.type = d.type
  left join semantic s on s.id = d.id and s.type = d.type
  where l.id is not null or s.id is not null
  order by 2 desc, d.updated_at desc
  limit least(greatest(result_limit, 1), 100)
$$;
revoke all on function public.hybrid_search_rrf(text, vector, text, integer, integer) from public;
grant execute on function public.hybrid_search_rrf(text, vector, text, integer, integer) to service_role;
